export const projects = [
  {
    title: 'FUTSAL FIELD ONLINE RESERVATION SYSTEM',
    description: "Web for online futsal field reservations in the Karawang area.",
      image: '/images/Futsalin-Kuy-Web.png',
      tags: ['Codeigniter', 'Bootstrap', 'Mysql'],
    source: 'https://github.com/Fadhila36/futsal-kuy',
    visit: 'https://testwebunifyst.rf.gd/futsal/?i=1',
    id: 0,
  },
  {
    title: 'Chat Lecture',
    description:"Lecturer Web Chat, with templates in accordance with the applicable lecturer chat etiquette.",
    image: '/images/Web-Chat-Dosen.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Fadhila36/chat-dosen',
    visit: 'http://himatif.ubpkarawang.ac.id/chat-dosen/',
    id: 1,
  },
  {
    title: 'Teacher Education and Elementary School of Buana Perjuangan Karawang University',
    description: " Web for Teacher Education Study Program (PGSD) UBP Karawang.",
      image: '/images/pgsd.png',
      tags: ['Wordpress'],
    source: '#',
    visit: 'http://pgsd.ubpkarawang.ac.id/',
    id: 2,
  },
  {
    title: 'Pancasila Education and Citizenship of Buana Perjuangan Karawang University',
    description: "Web for Pancasila Education and Citizenship Study Program (PPKN) UBP Karawang.",
    image: '/images/ppkn.png',
    tags: ['Wordpress'],
    source: '#',
    visit: 'http://ppkn.ubpkarawang.ac.id/',
    id: 3,
  },
  {
    title: 'LPPM Buana Perjuangan Karawang University',
    description: "Web for LPPM UBP Karawang.",
    image: '/images/lppm.png',
    tags: ['Wordpress'],
    source: '#',
    visit: 'http://lppm.ubpkarawang.ac.id/',
    id: 4,
  },
  {
    title: 'Lapak Sayur Karawang',
    description: "Web for vegetable sales in Karawang.",
    image: '/images/Lapak-sayur.png',
    tags: ['Codeigniter', 'Bootstrap', 'Mysql'],
    source: '#',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Online Employee Management System (Sipengkol)',
    description: "Web for submission of online employee leave.",
    image: '/images/sipengkol.png',
    tags: ['Codeigniter', 'Bootstrap', 'Mysql', 'Ajax'],
    source: 'https://github.com/Fadhila36/sipengkol',
    visit: 'https://github.com/Fadhila36/sipengkol',
    id: 6,
  },
  {
    title: 'Lapak Karawang Finance Web Management',
    description: "Lapak Karawang Finance Web Management.",
    image: '/images/Manajemen-Keuangan.png',
    tags: ['Codeigniter', 'Bootstrap', 'Mysql'],
    source: '#',
    visit: '#',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey', },
  { year: 2017, text: 'Working as a web developer at Reepal', },
  { year: 2018, text: 'Internship as a web developer at Pusdatin UBP Karawang', },
  { year: 2019, text: 'Internship as a web developer at Pusdatin UBP Karawang', },
  { year: 2020, text: 'Internship as a web developer at Unifisyt', },
  { year: 2021, text: 'Worked as a freelance developer', },
];